[package]
name = "procfill"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.22"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
anyhow = "1.0"
rusqlite = { version = "0.32.0" }


[dev-dependencies]
tempfile = "3.8" 